version: '3.8'

services:
  mcp-omnisearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-omnisearch
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - BRAVE_API_KEY
      - BRAVE_ANSWER_API_KEY
      - TAVILY_API_KEY
      - KAGI_API_KEY
      - PERPLEXITY_API_KEY
      - EXA_API_KEY
      - SERPAPI_API_KEY
      - LINKUP_API_KEY
      - FIRECRAWL_API_KEY
      - GEMINI_API_KEY
      - YOU_API_KEY
      - JINA_AI_API_KEY
      - GITHUB_API_KEY
